### ISSUE TITLE
NoSuchMethodError: No virtual method toPath()

### ISSUE THREAD

**Issue by lparolari** [TheElectronWill/Night-Config#46] opened 2018-09-24 08:25 UTC
Hello!
I have a very big problem. 

I've tried to debug my Android application and I discovered that under Android 8, the method used to add the file watcher does not work. In particular the `file.toPath()` does not exist.

Here is the stack trace:
```
09-24 10:16:52.647 18557-18557/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.bcv.invadelite.apptest, PID: 18557
    java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
        at com.electronwill.nightconfig.core.file.FileWatcher.addWatch(FileWatcher.java:69)
        at com.electronwill.nightconfig.core.file.AutoreloadFileConfig.<init>(AutoreloadFileConfig.java:17)
        at com.electronwill.nightconfig.core.file.FileConfigBuilder.build(FileConfigBuilder.java:193)
        at it.bcv.invade.appdb.ConfigAdapter.<init>(ConfigAdapter.java:37)
        at it.bcv.invade.appdb.Db.<init>(Db.java:51)
        at it.bcv.invade.appdb.Db.init(Db.java:75)
        at it.bcv.invadelite.activities.StartActivity.initDatabase(StartActivity.java:161)
        at it.bcv.invadelite.activities.StartActivity.onCreate(StartActivity.java:123)
```

The file watcher method has the following implementation:

```java
public void addWatch(File file, Runnable changeHandler) throws IOException {
	addWatch(file.toPath(), changeHandler);
}
```
and the `toPath` gives me an error.

Can you change this in order to get the backward compatibility?

Thanks!

**Comment by TheElectronWill** [comment] 2018-09-24 18:08
Ah, that's annoying. I use nio for a lot of things, especially async FileConfigs and the FileWatcher :sweat_smile:.

I'll try to make a module **core_android** without using `java.nio.file`, but I can't guarantee to provide exactly the same features regarding the files.

**Comment by TheElectronWill** [comment] 2018-09-25 11:42
I've created the **core_android** module, which doesn't rely on the package `java.nio.file` (see 361af5fa04e08f20d664c660be836266f5c9dc2e).
The FileWatcher should work, but I couldn't implement async fileconfigs so every FileConfig will be in synchronized mode, regardless of your setting. @lparolari Could you test the core_android ?

**Comment by lparolari** [comment] 2018-09-26 08:27
@TheElectronWill yes, I'll try it, thank you!
Let me some time because I'm a bit busy..

However I found another problem perhaps off topic about your library but if you want to check it here is the link [https://stackoverflow.com/questions/52484989/noclassdeffounderror-no-sense](https://stackoverflow.com/questions/52484989/noclassdeffounderror-no-sense)

**Comment by TheElectronWill** [comment] 2018-09-27 16:29
I've answered on stackoverflow. I think that your error is caused by missing classes (namely: `java.util.function.Supplier`) in older versions of the Android API. `Supplier` is used by my FormatDetector, therefore the android tools can't compile the lambda correctly.

**Closed** 2018-10-13 10:08 UTC
Labels: android, enhancement
